2017-10-17 23:57:19,810 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2017-10-17 23:57:19,816 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'activate_service_account']
2017-10-17 23:57:19,821 DEBUG    root            Running [gcloud.auth.activate-service-account] with arguments: [--key-file: "~/key.json"]
2017-10-17 23:57:19,821 DEBUG    root            (gcloud.auth.activate-service-account) Unable to read file [~/key.json]: [Errno 2] No such file or directory: '~/key.json'
Traceback (most recent call last):
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 789, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 759, in Run
    resources = command_instance.Run(args)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/auth/activate_service_account.py", line 80, in Run
    file_content, is_json = _IsJsonFile(args.key_file)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/auth/activate_service_account.py", line 127, in _IsJsonFile
    content = files.GetFileOrStdinContents(filename, binary=True)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/core/util/files.py", line 970, in GetFileOrStdinContents
    return GetFileContents(path, binary=binary)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/core/util/files.py", line 947, in GetFileContents
    raise Error(u'Unable to read file [{0}]: {1}'.format(path, e))
Error: Unable to read file [~/key.json]: [Errno 2] No such file or directory: '~/key.json'
2017-10-17 23:57:19,824 ERROR    root            (gcloud.auth.activate-service-account) Unable to read file [~/key.json]: [Errno 2] No such file or directory: '~/key.json'
